### ISSUE TITLE
How to import openrtb.proto in custom extension ?

### ISSUE THREAD

**Issue by mzgupta** [google/openrtb#101]
@opinali 
I've included following openrtb dependency. 

`<!-- https://mvnrepository.com/artifact/com.google.openrtb/openrtb-core -->`
`<dependency>`
`    <groupId>com.google.openrtb</groupId>`
`    <artifactId>openrtb-core</artifactId>`
`    <version>1.2.1</version>`
`</dependency>`

In wiki it says we can use protobuf extension to support OpenRTB Extension. In order to do so MyExtension.proto has to import openrtb.proto as follow, but this will not work because protoc is unable to find openrtb.proto, which is present somewhere in the jar.

syntax = "proto2";
package com.mz.extension;
option java_outer_classname = "MyExtension";

import "openrtb.proto";  //Unable to find it from the class path.

**Comment by opinali** [comment]
This is a common difficulty with protobufs + Maven, there's no good building support, at least last time I checked, and imports / dependenciesfrom external protos have to be resolved manually. What I do is using the maven-download-plugin, see here:

https://github.com/google/openrtb-doubleclick/blob/1.2.3/doubleclick-openrtb/pom.xml

Basically, you need to make the pom download external protos, then use maven-antrun-plugin to run javac on that and finally use build-helper-maven-plugin to add this compikled code to the build path for the rest of the Maven project. Lots of maven boilerplate but works well.

**Comment by mzgupta** [comment]
@opinali 
Thank you for your response. I would follow your step. One more question any plan to update to OpenRtb 2.5 in near future.

**Comment by opinali** [comment]
The short answer is yes, we're committed to support new releases of OpenRTB as they come, but there's no public schedule for specific releases. Best thing you can do is communicate any urgency to your DoubleClick account manager. ;-)

**Comment by YoavNordmann** [comment]
I was able to solve this as follows:
in my new *.proto file I added the import as so: 
`import "openrtb.proto";`

I then added the dependency as usual in maven.

I used the `protobuf-maven-plugin` plugin which makes me put the .proto files in the "src.main.proto" directory, but the import works and code is being generated as reuested.

**Comment by opinali** [comment]
Hi Yoav, checking your messages now -- is this related to issue #107 or that one is unsolved?

**Comment by YoavNordmann** [comment]
Hi
I just thought I would share how I succeeded.
As for issue #107 it is still unresolved.

Yoav
