### ISSUE TITLE
Fix miniumum JDK version in README.md

### ISSUE THREAD

**Issue by yosske** [google/openrtb#122]
The "Building Notes" in the README.md file says the minumum JDK for building is:

> "JDK 7" 

Instead Of:

> "JDK 8"

JDK 8 is needed ever since this fix was done:
https://github.com/google/openrtb/blob/master/CHANGELOG.md#version-097-29-10-2015

Thanks :)

**Comment by opinali** [comment]
Thanks for the heads up, fixed the readme to mention correct versions for JDK and also protoc. :)
