### ISSUE TITLE
Cannot find VideoBidResponseProtocol when running example

### ISSUE THREAD

**Issue by littlejin** [google/openrtb#127]
Hi,

When I try to run the example in wiki,

BidRequest request = BidRequest.newBuilder()
    .setId("1")
    .addImp(Imp.newBuilder()
        .setId("1")
        .setBidfloor(4000)
        .setVideo(Video.newBuilder()
            .setLinearity(VideoLinearity.LINEAR)
            .addProtocols(VideoBidResponseProtocol.VAST_3_0)
            .setW(640)
            .setH(480)))
    .build();

I cannot find class VideoBidResponseProtocol

Is it remove from the current build of this project ?

**Comment by opinali** [comment]
Sorry, that sample code was outdated--fixed it now.
