### ISSUE TITLE
ContentCategory enum and corresponding category fields

### ISSUE THREAD

**Issue by kkharma** [google/openrtb#30]
there are a number of fields (cat, bcat, etc.) that refer to list 5.1, which is a ContentCategory enum.  however, all of these fields are typed as string.  should they not be typed as ContentCategory?

**Comment by opinali** [comment]
That's a good idea; the spec uses ints or strings everywhere for these things but we can always use a higher-level type like enum in the model and then translate in the JSON serializer. It seems the ContentCategory fields are the only ones that missed this improvement, will fix this next release.

**Comment by opinali** [comment]
Fix will be in 0.8.1 soon.
