### ISSUE TITLE
Add builder instance as argument of public parsing methods in OpenRtbJsonReader

### ISSUE THREAD

**Issue by thaDude** [google/openrtb#56]
For methods like [OpenRtbJsonReader#parseBid(JsonParser par)](https://github.com/google/openrtb/blob/master/openrtb-core/src/main/java/com/google/openrtb/json/OpenRtbJsonReader.java#L1354) - would it make sense to add the builder instance to the argument list instead of creating the instance inside the method?

I have the use case where bid instances are added as an extension to a bid request's impression(s) - if I could pass an external `Bid.Builder` instance to the above parsing method I could leverage OpenRtbJsonReader's implementation inside my extension reader's `OpenRtbJsonExtReader<Impression.Builder, Bid.Builder>#read(Impression.Builder msg, Bid.Builder ext, JsonParser par)` method by just calling `OpenRtbJsonReader#parseBid(ext, par)`.

**Comment by opinali** [comment]
This is a tradeoff, the builder parameter would certainly help your use case, but it's much less convenient for the general case where all callers would need code like:

    Bid.Builder bid = Bid.newBuilder();
    readBid(par, bid);
    seatBid.addBid(bid);

I can make that better by returning the same builder passed as parameter:

    seatBid.addBid(readBid(par, Bid.newBuilder()));

But it's still more code, and that's not even the most important thing: I lose the ability to control creation of that builder in the `readBid()` method. This is important for example if I want to optimize all those read methods so they don't even allocate a builder (and return `null`) if the JSON object is an empty `{}`, which is something that can happen inside sloppily-created messages. (Avoiding to set a dummy child object on desserialization will also prevent serializing it back to `{}` from the same model, if you need to do that.) It's not a big impact in terms of performance, so I didn't put the time yet for that change, but I still find that valuable as a way to ensure canonicalization of messages: in scenarios like persistent data or test data, you want if possible that the same "logical" message results in the exact same in-memory model / same JSON, that makes everything more efficient and reliable (comparisons, indexing and whatever you need to do).

In your use case you can do this: `ext.mergeFrom(readBid(par))`. That switches the inconvenience from some extra code to your use case :) but other than that, should work.

**Comment by thaDude** [comment]
Thank you for the reply. Yeah, `ext.mergeFrom(readBid(par))` is probably what I was looking for. I am closing this issue.
