### ISSUE TITLE
Reading multiple extensions of the same message type with different name

### ISSUE THREAD

**Issue by thaDude** [google/openrtb#57]
Hello,

I am trying to understand if `OpenRtbJsonExtReader` is capable of dealing with the case where a message is extended several times with another message with different extension name. This concerns version 0.8.1 of the library. My example is as follows:

I extended OpenRTB like so:

```
...

// Extended twice with customer Event message using different extension name.
extend com.google.openrtb.BidResponse.SeatBid.Bid { 
  optional Event impression = 188;
  optional Event click = 189;
  ...
}

...
```

and implemented `OpenRtbJsonExtReader<Bid.Builder, Event.Builder>` like so:

````
public class EventExtensionReader extends OpenRtbJsonExtReader<Bid.Builder, Event.Builder> {

    public EventExtensionReader(GeneratedExtension<?, ?> key) {
        super(key);
    }

    @Override
    protected void read(Bid.Builder msg, Event.Builder ext, JsonParser par) throws IOException {
        // Determine if this is a click or impression by checking current parameter name.
        String fieldName = getCurrentName(par);
        Type type = Type.valueOf(getCurrentName(par).toUpperCase());
        switch (type) {
            case IMPRESSION:
                EventUtils.read(ext, type, par);
                // msg.setExtension(MyProto.impression, EventUtils.read(ext, type, par).build());
                return;
            case CLICK:
                EventUtils.read(ext, type, par);
                // msg.setExtension(MyProto.click, EventUtils.read(ext, type, par).build());
                return;
            default:
                break;
        }
        return;
    }

}
```

The `OpenRtbJsonReader` for extensions of bids is instantiated like:
````
    private OpenRtbJsonReader reader = jsonFactory
        .register(new EventExtensionReader(MyProto.click), Bid.Builder.class)
        .register(new EventExtensionReader(MyProto.impression), Bid.Builder.class)
        .newReader();
```

With the above reader the parsed bid will only contain one event extension only! Further, the name will be "click" but the Event instance will be that of the impression.

The only way to properly de-serialise both extensions is to explicitly set the extension - see commented code - but it seems wrong. Is there something I am missing?

Thanks

/David

**Comment by opinali** [comment]
This one will take some time — the JSON extension API is already the part of this library I'm less happy about. Good that for now you have a workaround, meanwhile I'm lookingo into a real improvement for this API instead of just adding another special case.

**Comment by opinali** [comment]
Ok, the latest code on master should fix this last limitation, also it does the big revamp of the JSON extension API that I'd been putting off for too long. This required breaking changes but not too bad and the new code is simpler–most readers will lose one generic parameter so you don't need to use a dummy `..., Message.Builder>`; others will have to change the base class and lose the first parameter in the `read()` method. Some work too for easier development like proper abstract methods and more error handling and logging.

I'm afraid testing this can be difficult before the next Open Bidder is released because the code in master for these libraries include other changes (even a rare breaking change in the AdX protocol), but there are new unit tests that reproduce your use case so hopefully this will solve the problem.

**Comment by thaDude** [comment]
Thank  you for looking into this. I'll test this in the context of the next OB release!

**Comment by thaDude** [comment]
Hi, just for completion's sake - my original work-around did not have the intended effect. I just settled for something like this:

```
public class EventExtensionReader extends OpenRtbJsonExtReader<Bid.Builder, Event.Builder> {

    private String keyName;
    
    public EventExtensionReader(GeneratedExtension<?, ?> key) {
        super(key);
        this.keyName = key.getDescriptor().getName();
    }

    @Override
    protected void read(Bid.Builder msg, Event.Builder ext, JsonParser par) throws IOException {
        String fieldName = getCurrentName(par);
        if (keyName.equals(fieldName) == false) {
            return;
        }
        Type type = Type.valueOf(getCurrentName(par).toUpperCase());
        EventUtils.read(ext, type, par);
    }

}
```

The only drawback of this solution is that it requires a different reader instance for each key type - click, impression in my case. The read method returns early if the field name does not match the key. I can live with that.
