### ISSUE TITLE
Implement OpenRTB 2.4, Native 1.1

### ISSUE THREAD

**Issue by opinali** [google/openrtb#94]

**Comment by philipphoffmann** [comment]
Any plan on when this release is going to happen? Just asking, no pressure :)

**Comment by opinali** [comment]
Hi @philipphoffmann, as you see we're finally working on this... slowly, because the user demand has been slow too but finally picking up. :) So this support will come in two phases:

1. The core openrtb project (this one) will include the updated protos and JSON support. This is coming soon in v1.1.0, maybe next week but two weeks from now I'd say.
2. For people bidding on AdX who may also need the sibling [openrtb-doubleclick](https://github.com/google/openrtb-doubleclick) library, it will have a matching, simultaneous v1.1.0 release that will initially have no functional changes, just compatibility with openrtb core v1.1.0. Later, we'll have v1.1.x updates that will incrementally add new mappings (e.g. for the `format` field and others useful for AdX), these will roll out simultaneously with updates in the native OpenRTB protocol support from AdX so people can use the new stuff with or without this library; my expectation is having this done by EOY.

**Comment by philipphoffmann** [comment]
alright, thx @opinali :)
