### ISSUE TITLE
Compat branch releases

### ISSUE THREAD

**Issue by dhamilton** [google/openrtb#98]
Hi, are there any plans to release the compat branch for v1.1 of openrtb-core and doubleclick-openrtb?

**Comment by opinali** [comment]
Yes, it's just lagging a little behind but this should be out today or tomorrow. :)

**Comment by dhamilton** [comment]
Awesome, thanks!

**Comment by dhamilton** [comment]
I just pulled the release from Maven Central. Thanks for the quick turnaround!

**Comment by opinali** [comment]
No problem, I was expecting more merging work for this update but it was easier than expected.
